// Copyright © 2016 Matthias Benkort
// Use of this source code is governed by the MPL 2.0 license that can be found in the LICENSE file.

package currencies

var currencies = map[string]Currency{
	"AED": Currency{
		Alpha3:   "AED",
		Numeric:  "784",
		Decimals: 2,
		Name:     "United Arab Emirates dirham",
	},
	"AFN": Currency{
		Alpha3:   "AFN",
		Numeric:  "971",
		Decimals: 2,
		Name:     "Afghan afghani",
	},
	"ALL": Currency{
		Alpha3:   "ALL",
		Numeric:  "8",
		Decimals: 2,
		Name:     "Albanian lek",
	},
	"AMD": Currency{
		Alpha3:   "AMD",
		Numeric:  "51",
		Decimals: 2,
		Name:     "Armenian dram",
	},
	"ANG": Currency{
		Alpha3:   "ANG",
		Numeric:  "532",
		Decimals: 2,
		Name:     "Netherlands Antillean guilder",
	},
	"AOA": Currency{
		Alpha3:   "AOA",
		Numeric:  "973",
		Decimals: 2,
		Name:     "Angolan kwanza",
	},
	"ARS": Currency{
		Alpha3:   "ARS",
		Numeric:  "32",
		Decimals: 2,
		Name:     "Argentine peso",
	},
	"AUD": Currency{
		Alpha3:   "AUD",
		Numeric:  "36",
		Decimals: 2,
		Name:     "Australian dollar",
	},
	"AWG": Currency{
		Alpha3:   "AWG",
		Numeric:  "533",
		Decimals: 2,
		Name:     "Aruban florin",
	},
	"AZN": Currency{
		Alpha3:   "AZN",
		Numeric:  "944",
		Decimals: 2,
		Name:     "Azerbaijani manat",
	},
	"BAM": Currency{
		Alpha3:   "BAM",
		Numeric:  "977",
		Decimals: 2,
		Name:     "Bosnia and Herzegovina convertible mark",
	},
	"BBD": Currency{
		Alpha3:   "BBD",
		Numeric:  "52",
		Decimals: 2,
		Name:     "Barbados dollar",
	},
	"BDT": Currency{
		Alpha3:   "BDT",
		Numeric:  "50",
		Decimals: 2,
		Name:     "Bangladeshi taka",
	},
	"BGN": Currency{
		Alpha3:   "BGN",
		Numeric:  "975",
		Decimals: 2,
		Name:     "Bulgarian lev",
	},
	"BHD": Currency{
		Alpha3:   "BHD",
		Numeric:  "48",
		Decimals: 3,
		Name:     "Bahraini dinar",
	},
	"BIF": Currency{
		Alpha3:   "BIF",
		Numeric:  "108",
		Decimals: 0,
		Name:     "Burundian franc",
	},
	"BMD": Currency{
		Alpha3:   "BMD",
		Numeric:  "60",
		Decimals: 2,
		Name:     "Bermudian dollar (customarily known as Bermuda dollar)",
	},
	"BND": Currency{
		Alpha3:   "BND",
		Numeric:  "96",
		Decimals: 2,
		Name:     "Brunei dollar",
	},
	"BOB": Currency{
		Alpha3:   "BOB",
		Numeric:  "68",
		Decimals: 2,
		Name:     "Boliviano",
	},
	"BOV": Currency{
		Alpha3:   "BOV",
		Numeric:  "984",
		Decimals: 2,
		Name:     "Bolivian Mvdol (funds code)",
	},
	"BRL": Currency{
		Alpha3:   "BRL",
		Numeric:  "986",
		Decimals: 2,
		Name:     "Brazilian real",
	},
	"BSD": Currency{
		Alpha3:   "BSD",
		Numeric:  "44",
		Decimals: 2,
		Name:     "Bahamian dollar",
	},
	"BTN": Currency{
		Alpha3:   "BTN",
		Numeric:  "64",
		Decimals: 2,
		Name:     "Bhutanese ngultrum",
	},
	"BWP": Currency{
		Alpha3:   "BWP",
		Numeric:  "72",
		Decimals: 2,
		Name:     "Botswana pula",
	},
	"BYR": Currency{
		Alpha3:   "BYR",
		Numeric:  "974",
		Decimals: 0,
		Name:     "Belarusian ruble",
	},
	"BZD": Currency{
		Alpha3:   "BZD",
		Numeric:  "84",
		Decimals: 2,
		Name:     "Belize dollar",
	},
	"CAD": Currency{
		Alpha3:   "CAD",
		Numeric:  "124",
		Decimals: 2,
		Name:     "Canadian dollar",
	},
	"CDF": Currency{
		Alpha3:   "CDF",
		Numeric:  "976",
		Decimals: 2,
		Name:     "Congolese franc",
	},
	"CHE": Currency{
		Alpha3:   "CHE",
		Numeric:  "947",
		Decimals: 2,
		Name:     "WIR Euro (complementary currency)",
	},
	"CHF": Currency{
		Alpha3:   "CHF",
		Numeric:  "756",
		Decimals: 2,
		Name:     "Swiss franc",
	},
	"CHW": Currency{
		Alpha3:   "CHW",
		Numeric:  "948",
		Decimals: 2,
		Name:     "WIR Franc (complementary currency)",
	},
	"CLF": Currency{
		Alpha3:   "CLF",
		Numeric:  "990",
		Decimals: 0,
		Name:     "Unidad de Fomento (funds code)",
	},
	"CLP": Currency{
		Alpha3:   "CLP",
		Numeric:  "152",
		Decimals: 0,
		Name:     "Chilean peso",
	},
	"CNY": Currency{
		Alpha3:   "CNY",
		Numeric:  "156",
		Decimals: 2,
		Name:     "Chinese yuan",
	},
	"COP": Currency{
		Alpha3:   "COP",
		Numeric:  "170",
		Decimals: 2,
		Name:     "Colombian peso",
	},
	"COU": Currency{
		Alpha3:   "COU",
		Numeric:  "970",
		Decimals: 2,
		Name:     "Unidad de Valor Real",
	},
	"CRC": Currency{
		Alpha3:   "CRC",
		Numeric:  "188",
		Decimals: 2,
		Name:     "Costa Rican colon",
	},
	"CUC": Currency{
		Alpha3:   "CUC",
		Numeric:  "931",
		Decimals: 2,
		Name:     "Cuban convertible peso",
	},
	"CUP": Currency{
		Alpha3:   "CUP",
		Numeric:  "192",
		Decimals: 2,
		Name:     "Cuban peso",
	},
	"CVE": Currency{
		Alpha3:   "CVE",
		Numeric:  "132",
		Decimals: 0,
		Name:     "Cape Verde escudo",
	},
	"CZK": Currency{
		Alpha3:   "CZK",
		Numeric:  "203",
		Decimals: 2,
		Name:     "Czech koruna",
	},
	"DJF": Currency{
		Alpha3:   "DJF",
		Numeric:  "262",
		Decimals: 0,
		Name:     "Djiboutian franc",
	},
	"DKK": Currency{
		Alpha3:   "DKK",
		Numeric:  "208",
		Decimals: 2,
		Name:     "Danish krone",
	},
	"DOP": Currency{
		Alpha3:   "DOP",
		Numeric:  "214",
		Decimals: 2,
		Name:     "Dominican peso",
	},
	"DZD": Currency{
		Alpha3:   "DZD",
		Numeric:  "12",
		Decimals: 2,
		Name:     "Algerian dinar",
	},
	"EGP": Currency{
		Alpha3:   "EGP",
		Numeric:  "818",
		Decimals: 2,
		Name:     "Egyptian pound",
	},
	"ERN": Currency{
		Alpha3:   "ERN",
		Numeric:  "232",
		Decimals: 2,
		Name:     "Eritrean nakfa",
	},
	"ETB": Currency{
		Alpha3:   "ETB",
		Numeric:  "230",
		Decimals: 2,
		Name:     "Ethiopian birr",
	},
	"EUR": Currency{
		Alpha3:   "EUR",
		Numeric:  "978",
		Decimals: 2,
		Name:     "Euro",
	},
	"FJD": Currency{
		Alpha3:   "FJD",
		Numeric:  "242",
		Decimals: 2,
		Name:     "Fiji dollar",
	},
	"FKP": Currency{
		Alpha3:   "FKP",
		Numeric:  "238",
		Decimals: 2,
		Name:     "Falkland Islands pound",
	},
	"GBP": Currency{
		Alpha3:   "GBP",
		Numeric:  "826",
		Decimals: 2,
		Name:     "Pound sterling",
	},
	"GEL": Currency{
		Alpha3:   "GEL",
		Numeric:  "981",
		Decimals: 2,
		Name:     "Georgian lari",
	},
	"GHS": Currency{
		Alpha3:   "GHS",
		Numeric:  "936",
		Decimals: 2,
		Name:     "Ghanaian cedi",
	},
	"GIP": Currency{
		Alpha3:   "GIP",
		Numeric:  "292",
		Decimals: 2,
		Name:     "Gibraltar pound",
	},
	"GMD": Currency{
		Alpha3:   "GMD",
		Numeric:  "270",
		Decimals: 2,
		Name:     "Gambian dalasi",
	},
	"GNF": Currency{
		Alpha3:   "GNF",
		Numeric:  "324",
		Decimals: 0,
		Name:     "Guinean franc",
	},
	"GTQ": Currency{
		Alpha3:   "GTQ",
		Numeric:  "320",
		Decimals: 2,
		Name:     "Guatemalan quetzal",
	},
	"GYD": Currency{
		Alpha3:   "GYD",
		Numeric:  "328",
		Decimals: 2,
		Name:     "Guyanese dollar",
	},
	"HKD": Currency{
		Alpha3:   "HKD",
		Numeric:  "344",
		Decimals: 2,
		Name:     "Hong Kong dollar",
	},
	"HNL": Currency{
		Alpha3:   "HNL",
		Numeric:  "340",
		Decimals: 2,
		Name:     "Honduran lempira",
	},
	"HRK": Currency{
		Alpha3:   "HRK",
		Numeric:  "191",
		Decimals: 2,
		Name:     "Croatian kuna",
	},
	"HTG": Currency{
		Alpha3:   "HTG",
		Numeric:  "332",
		Decimals: 2,
		Name:     "Haitian gourde",
	},
	"HUF": Currency{
		Alpha3:   "HUF",
		Numeric:  "348",
		Decimals: 2,
		Name:     "Hungarian forint",
	},
	"IDR": Currency{
		Alpha3:   "IDR",
		Numeric:  "360",
		Decimals: 2,
		Name:     "Indonesian rupiah",
	},
	"ILS": Currency{
		Alpha3:   "ILS",
		Numeric:  "376",
		Decimals: 2,
		Name:     "Israeli new shekel",
	},
	"INR": Currency{
		Alpha3:   "INR",
		Numeric:  "356",
		Decimals: 2,
		Name:     "Indian rupee",
	},
	"IQD": Currency{
		Alpha3:   "IQD",
		Numeric:  "368",
		Decimals: 3,
		Name:     "Iraqi dinar",
	},
	"IRR": Currency{
		Alpha3:   "IRR",
		Numeric:  "364",
		Decimals: 0,
		Name:     "Iranian rial",
	},
	"ISK": Currency{
		Alpha3:   "ISK",
		Numeric:  "352",
		Decimals: 0,
		Name:     "Icelandic króna",
	},
	"JMD": Currency{
		Alpha3:   "JMD",
		Numeric:  "388",
		Decimals: 2,
		Name:     "Jamaican dollar",
	},
	"JOD": Currency{
		Alpha3:   "JOD",
		Numeric:  "400",
		Decimals: 3,
		Name:     "Jordanian dinar",
	},
	"JPY": Currency{
		Alpha3:   "JPY",
		Numeric:  "392",
		Decimals: 0,
		Name:     "Japanese yen",
	},
	"KES": Currency{
		Alpha3:   "KES",
		Numeric:  "404",
		Decimals: 2,
		Name:     "Kenyan shilling",
	},
	"KGS": Currency{
		Alpha3:   "KGS",
		Numeric:  "417",
		Decimals: 2,
		Name:     "Kyrgyzstani som",
	},
	"KHR": Currency{
		Alpha3:   "KHR",
		Numeric:  "116",
		Decimals: 2,
		Name:     "Cambodian riel",
	},
	"KMF": Currency{
		Alpha3:   "KMF",
		Numeric:  "174",
		Decimals: 0,
		Name:     "Comoro franc",
	},
	"KPW": Currency{
		Alpha3:   "KPW",
		Numeric:  "408",
		Decimals: 0,
		Name:     "North Korean won",
	},
	"KRW": Currency{
		Alpha3:   "KRW",
		Numeric:  "410",
		Decimals: 0,
		Name:     "South Korean won",
	},
	"KWD": Currency{
		Alpha3:   "KWD",
		Numeric:  "414",
		Decimals: 3,
		Name:     "Kuwaiti dinar",
	},
	"KYD": Currency{
		Alpha3:   "KYD",
		Numeric:  "136",
		Decimals: 2,
		Name:     "Cayman Islands dollar",
	},
	"KZT": Currency{
		Alpha3:   "KZT",
		Numeric:  "398",
		Decimals: 2,
		Name:     "Kazakhstani tenge",
	},
	"LAK": Currency{
		Alpha3:   "LAK",
		Numeric:  "418",
		Decimals: 0,
		Name:     "Lao kip",
	},
	"LBP": Currency{
		Alpha3:   "LBP",
		Numeric:  "422",
		Decimals: 0,
		Name:     "Lebanese pound",
	},
	"LKR": Currency{
		Alpha3:   "LKR",
		Numeric:  "144",
		Decimals: 2,
		Name:     "Sri Lankan rupee",
	},
	"LRD": Currency{
		Alpha3:   "LRD",
		Numeric:  "430",
		Decimals: 2,
		Name:     "Liberian dollar",
	},
	"LSL": Currency{
		Alpha3:   "LSL",
		Numeric:  "426",
		Decimals: 2,
		Name:     "Lesotho loti",
	},
	"LTL": Currency{
		Alpha3:   "LTL",
		Numeric:  "440",
		Decimals: 2,
		Name:     "Lithuanian litas",
	},
	"LVL": Currency{
		Alpha3:   "LVL",
		Numeric:  "428",
		Decimals: 2,
		Name:     "Latvian lats",
	},
	"LYD": Currency{
		Alpha3:   "LYD",
		Numeric:  "434",
		Decimals: 3,
		Name:     "Libyan dinar",
	},
	"MAD": Currency{
		Alpha3:   "MAD",
		Numeric:  "504",
		Decimals: 2,
		Name:     "Moroccan dirham",
	},
	"MDL": Currency{
		Alpha3:   "MDL",
		Numeric:  "498",
		Decimals: 2,
		Name:     "Moldovan leu",
	},
	"MGA": Currency{
		Alpha3:   "MGA",
		Numeric:  "969",
		Decimals: 0,
		Name:     "Malagasy ariary",
	},
	"MKD": Currency{
		Alpha3:   "MKD",
		Numeric:  "807",
		Decimals: 0,
		Name:     "Macedonian denar",
	},
	"MMK": Currency{
		Alpha3:   "MMK",
		Numeric:  "104",
		Decimals: 0,
		Name:     "Myanma kyat",
	},
	"MNT": Currency{
		Alpha3:   "MNT",
		Numeric:  "496",
		Decimals: 2,
		Name:     "Mongolian tugrik",
	},
	"MOP": Currency{
		Alpha3:   "MOP",
		Numeric:  "446",
		Decimals: 2,
		Name:     "Macanese pataca",
	},
	"MRO": Currency{
		Alpha3:   "MRO",
		Numeric:  "478",
		Decimals: 0,
		Name:     "Mauritanian ouguiya",
	},
	"MUR": Currency{
		Alpha3:   "MUR",
		Numeric:  "480",
		Decimals: 2,
		Name:     "Mauritian rupee",
	},
	"MVR": Currency{
		Alpha3:   "MVR",
		Numeric:  "462",
		Decimals: 2,
		Name:     "Maldivian rufiyaa",
	},
	"MWK": Currency{
		Alpha3:   "MWK",
		Numeric:  "454",
		Decimals: 2,
		Name:     "Malawian kwacha",
	},
	"MXN": Currency{
		Alpha3:   "MXN",
		Numeric:  "484",
		Decimals: 2,
		Name:     "Mexican peso",
	},
	"MXV": Currency{
		Alpha3:   "MXV",
		Numeric:  "979",
		Decimals: 2,
		Name:     "Mexican Unidad de Inversion (UDI) (funds code)",
	},
	"MYR": Currency{
		Alpha3:   "MYR",
		Numeric:  "458",
		Decimals: 2,
		Name:     "Malaysian ringgit",
	},
	"MZN": Currency{
		Alpha3:   "MZN",
		Numeric:  "943",
		Decimals: 2,
		Name:     "Mozambican metical",
	},
	"NAD": Currency{
		Alpha3:   "NAD",
		Numeric:  "516",
		Decimals: 2,
		Name:     "Namibian dollar",
	},
	"NGN": Currency{
		Alpha3:   "NGN",
		Numeric:  "566",
		Decimals: 2,
		Name:     "Nigerian naira",
	},
	"NIO": Currency{
		Alpha3:   "NIO",
		Numeric:  "558",
		Decimals: 2,
		Name:     "Nicaraguan córdoba",
	},
	"NOK": Currency{
		Alpha3:   "NOK",
		Numeric:  "578",
		Decimals: 2,
		Name:     "Norwegian krone",
	},
	"NPR": Currency{
		Alpha3:   "NPR",
		Numeric:  "524",
		Decimals: 2,
		Name:     "Nepalese rupee",
	},
	"NZD": Currency{
		Alpha3:   "NZD",
		Numeric:  "554",
		Decimals: 2,
		Name:     "New Zealand dollar",
	},
	"OMR": Currency{
		Alpha3:   "OMR",
		Numeric:  "512",
		Decimals: 3,
		Name:     "Omani rial",
	},
	"PAB": Currency{
		Alpha3:   "PAB",
		Numeric:  "590",
		Decimals: 2,
		Name:     "Panamanian balboa",
	},
	"PEN": Currency{
		Alpha3:   "PEN",
		Numeric:  "604",
		Decimals: 2,
		Name:     "Peruvian nuevo sol",
	},
	"PGK": Currency{
		Alpha3:   "PGK",
		Numeric:  "598",
		Decimals: 2,
		Name:     "Papua New Guinean kina",
	},
	"PHP": Currency{
		Alpha3:   "PHP",
		Numeric:  "608",
		Decimals: 2,
		Name:     "Philippine peso",
	},
	"PKR": Currency{
		Alpha3:   "PKR",
		Numeric:  "586",
		Decimals: 2,
		Name:     "Pakistani rupee",
	},
	"PLN": Currency{
		Alpha3:   "PLN",
		Numeric:  "985",
		Decimals: 2,
		Name:     "Polish złoty",
	},
	"PYG": Currency{
		Alpha3:   "PYG",
		Numeric:  "600",
		Decimals: 0,
		Name:     "Paraguayan guaraní",
	},
	"QAR": Currency{
		Alpha3:   "QAR",
		Numeric:  "634",
		Decimals: 2,
		Name:     "Qatari riyal",
	},
	"RON": Currency{
		Alpha3:   "RON",
		Numeric:  "946",
		Decimals: 2,
		Name:     "Romanian new leu",
	},
	"RSD": Currency{
		Alpha3:   "RSD",
		Numeric:  "941",
		Decimals: 2,
		Name:     "Serbian dinar",
	},
	"RUB": Currency{
		Alpha3:   "RUB",
		Numeric:  "643",
		Decimals: 2,
		Name:     "Russian rouble",
	},
	"RWF": Currency{
		Alpha3:   "RWF",
		Numeric:  "646",
		Decimals: 0,
		Name:     "Rwandan franc",
	},
	"SAR": Currency{
		Alpha3:   "SAR",
		Numeric:  "682",
		Decimals: 2,
		Name:     "Saudi riyal",
	},
	"SBD": Currency{
		Alpha3:   "SBD",
		Numeric:  "90",
		Decimals: 2,
		Name:     "Solomon Islands dollar",
	},
	"SCR": Currency{
		Alpha3:   "SCR",
		Numeric:  "690",
		Decimals: 2,
		Name:     "Seychelles rupee",
	},
	"SDG": Currency{
		Alpha3:   "SDG",
		Numeric:  "938",
		Decimals: 2,
		Name:     "Sudanese pound",
	},
	"SEK": Currency{
		Alpha3:   "SEK",
		Numeric:  "752",
		Decimals: 2,
		Name:     "Swedish krona/kronor",
	},
	"SGD": Currency{
		Alpha3:   "SGD",
		Numeric:  "702",
		Decimals: 2,
		Name:     "Singapore dollar",
	},
	"SHP": Currency{
		Alpha3:   "SHP",
		Numeric:  "654",
		Decimals: 2,
		Name:     "Saint Helena pound",
	},
	"SLL": Currency{
		Alpha3:   "SLL",
		Numeric:  "694",
		Decimals: 0,
		Name:     "Sierra Leonean leone",
	},
	"SOS": Currency{
		Alpha3:   "SOS",
		Numeric:  "706",
		Decimals: 2,
		Name:     "Somali shilling",
	},
	"SRD": Currency{
		Alpha3:   "SRD",
		Numeric:  "968",
		Decimals: 2,
		Name:     "Surinamese dollar",
	},
	"SSP": Currency{
		Alpha3:   "SSP",
		Numeric:  "728",
		Decimals: 2,
		Name:     "South Sudanese pound",
	},
	"STD": Currency{
		Alpha3:   "STD",
		Numeric:  "678",
		Decimals: 0,
		Name:     "São Tomé and Príncipe dobra",
	},
	"SYP": Currency{
		Alpha3:   "SYP",
		Numeric:  "760",
		Decimals: 2,
		Name:     "Syrian pound",
	},
	"SZL": Currency{
		Alpha3:   "SZL",
		Numeric:  "748",
		Decimals: 2,
		Name:     "Swazi lilangeni",
	},
	"THB": Currency{
		Alpha3:   "THB",
		Numeric:  "764",
		Decimals: 2,
		Name:     "Thai baht",
	},
	"TJS": Currency{
		Alpha3:   "TJS",
		Numeric:  "972",
		Decimals: 2,
		Name:     "Tajikistani somoni",
	},
	"TMT": Currency{
		Alpha3:   "TMT",
		Numeric:  "934",
		Decimals: 2,
		Name:     "Turkmenistani manat",
	},
	"TND": Currency{
		Alpha3:   "TND",
		Numeric:  "788",
		Decimals: 3,
		Name:     "Tunisian dinar",
	},
	"TOP": Currency{
		Alpha3:   "TOP",
		Numeric:  "776",
		Decimals: 2,
		Name:     "Tongan paʻanga",
	},
	"TRY": Currency{
		Alpha3:   "TRY",
		Numeric:  "949",
		Decimals: 2,
		Name:     "Turkish lira",
	},
	"TTD": Currency{
		Alpha3:   "TTD",
		Numeric:  "780",
		Decimals: 2,
		Name:     "Trinidad and Tobago dollar",
	},
	"TWD": Currency{
		Alpha3:   "TWD",
		Numeric:  "901",
		Decimals: 2,
		Name:     "New Taiwan dollar",
	},
	"TZS": Currency{
		Alpha3:   "TZS",
		Numeric:  "834",
		Decimals: 2,
		Name:     "Tanzanian shilling",
	},
	"UAH": Currency{
		Alpha3:   "UAH",
		Numeric:  "980",
		Decimals: 2,
		Name:     "Ukrainian hryvnia",
	},
	"UGX": Currency{
		Alpha3:   "UGX",
		Numeric:  "800",
		Decimals: 2,
		Name:     "Ugandan shilling",
	},
	"USD": Currency{
		Alpha3:   "USD",
		Numeric:  "840",
		Decimals: 2,
		Name:     "United States dollar",
	},
	"USN": Currency{
		Alpha3:   "USN",
		Numeric:  "997",
		Decimals: 2,
		Name:     "United States dollar (next day) (funds code)",
	},
	"USS": Currency{
		Alpha3:   "USS",
		Numeric:  "998",
		Decimals: 2,
		Name:     "United States dollar (same day) (funds code) (one source[who?] claims it is no longer used, but it is still on the ISO 4217-MA list)",
	},
	"UYI": Currency{
		Alpha3:   "UYI",
		Numeric:  "940",
		Decimals: 0,
		Name:     "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)",
	},
	"UYU": Currency{
		Alpha3:   "UYU",
		Numeric:  "858",
		Decimals: 2,
		Name:     "Uruguayan peso",
	},
	"UZS": Currency{
		Alpha3:   "UZS",
		Numeric:  "860",
		Decimals: 2,
		Name:     "Uzbekistan som",
	},
	"VEF": Currency{
		Alpha3:   "VEF",
		Numeric:  "937",
		Decimals: 2,
		Name:     "Venezuelan bolívar fuerte",
	},
	"VND": Currency{
		Alpha3:   "VND",
		Numeric:  "704",
		Decimals: 0,
		Name:     "Vietnamese dong",
	},
	"VUV": Currency{
		Alpha3:   "VUV",
		Numeric:  "548",
		Decimals: 0,
		Name:     "Vanuatu vatu",
	},
	"WST": Currency{
		Alpha3:   "WST",
		Numeric:  "882",
		Decimals: 2,
		Name:     "Samoan tala",
	},
	"XAF": Currency{
		Alpha3:   "XAF",
		Numeric:  "950",
		Decimals: 0,
		Name:     "CFA franc BEAC",
	},
	"XAG": Currency{
		Alpha3:   "XAG",
		Numeric:  "961",
		Decimals: 0,
		Name:     "Silver (one troy ounce)",
	},
	"XAU": Currency{
		Alpha3:   "XAU",
		Numeric:  "959",
		Decimals: 0,
		Name:     "Gold (one troy ounce)",
	},
	"XBA": Currency{
		Alpha3:   "XBA",
		Numeric:  "955",
		Decimals: 0,
		Name:     "European Composite Unit (EURCO) (bond market unit)",
	},
	"XBB": Currency{
		Alpha3:   "XBB",
		Numeric:  "956",
		Decimals: 0,
		Name:     "European Monetary Unit (E.M.U.-6) (bond market unit)",
	},
	"XBC": Currency{
		Alpha3:   "XBC",
		Numeric:  "957",
		Decimals: 0,
		Name:     "European Unit of Account 9 (E.U.A.-9) (bond market unit)",
	},
	"XBD": Currency{
		Alpha3:   "XBD",
		Numeric:  "958",
		Decimals: 0,
		Name:     "European Unit of Account 17 (E.U.A.-17) (bond market unit)",
	},
	"XCD": Currency{
		Alpha3:   "XCD",
		Numeric:  "951",
		Decimals: 2,
		Name:     "East Caribbean dollar",
	},
	"XDR": Currency{
		Alpha3:   "XDR",
		Numeric:  "960",
		Decimals: 0,
		Name:     "Special drawing rights",
	},
	"XFU": Currency{
		Alpha3:   "XFU",
		Numeric:  "Nil",
		Decimals: 0,
		Name:     "UIC franc (special settlement currency)",
	},
	"XOF": Currency{
		Alpha3:   "XOF",
		Numeric:  "952",
		Decimals: 0,
		Name:     "CFA franc BCEAO",
	},
	"XPD": Currency{
		Alpha3:   "XPD",
		Numeric:  "964",
		Decimals: 0,
		Name:     "Palladium (one troy ounce)",
	},
	"XPF": Currency{
		Alpha3:   "XPF",
		Numeric:  "953",
		Decimals: 0,
		Name:     "CFP franc",
	},
	"XPT": Currency{
		Alpha3:   "XPT",
		Numeric:  "962",
		Decimals: 0,
		Name:     "Platinum (one troy ounce)",
	},
	"XTS": Currency{
		Alpha3:   "XTS",
		Numeric:  "963",
		Decimals: 0,
		Name:     "Code reserved for testing purposes",
	},
	"XXX": Currency{
		Alpha3:   "XXX",
		Numeric:  "999",
		Decimals: 0,
		Name:     "No currency",
	},
	"YER": Currency{
		Alpha3:   "YER",
		Numeric:  "886",
		Decimals: 2,
		Name:     "Yemeni rial",
	},
	"ZAR": Currency{
		Alpha3:   "ZAR",
		Numeric:  "710",
		Decimals: 2,
		Name:     "South African rand",
	},
	"ZMW": Currency{
		Alpha3:   "ZMW",
		Numeric:  "967",
		Decimals: 2,
		Name:     "Zambian kwacha",
	},
}
