// Copyright © 2016 Matthias Benkort
// Use of this source code is governed by the MPL 2.0 license that can be found in the LICENSE file.

package countries

var countries = map[string]country{
	"AND": country{
		Country: Country{
			Alpha2:       "AD",
			Alpha3:       "AND",
			Numeric:      "020",
			DialingCodes: []string{"+376"},
			Name:         "Andorra",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"cat"},
	},
	"ARE": country{
		Country: Country{
			Alpha2:       "AE",
			Alpha3:       "ARE",
			Numeric:      "784",
			DialingCodes: []string{"+971"},
			Name:         "United Arab Emirates",
		},
		Currencies: []string{"AED"},
		Languages:  []string{"ara"},
	},
	"AFG": country{
		Country: Country{
			Alpha2:       "AF",
			Alpha3:       "AFG",
			Numeric:      "004",
			DialingCodes: []string{"+93"},
			Name:         "Afghanistan",
		},
		Currencies: []string{"AFN"},
		Languages:  []string{"pus"},
	},
	"ATG": country{
		Country: Country{
			Alpha2:       "AG",
			Alpha3:       "ATG",
			Numeric:      "028",
			DialingCodes: []string{"+1 268"},
			Name:         "Antigua And Barbuda",
		},
		Currencies: []string{"XCD"},
		Languages:  []string{"eng"},
	},
	"AIA": country{
		Country: Country{
			Alpha2:       "AI",
			Alpha3:       "AIA",
			Numeric:      "660",
			DialingCodes: []string{"+1 264"},
			Name:         "Anguilla",
		},
		Currencies: []string{"XCD"},
		Languages:  []string{"eng"},
	},
	"ALB": country{
		Country: Country{
			Alpha2:       "AL",
			Alpha3:       "ALB",
			Numeric:      "008",
			DialingCodes: []string{"+355"},
			Name:         "Albania",
		},
		Currencies: []string{"ALL"},
		Languages:  []string{"sqi"},
	},
	"ARM": country{
		Country: Country{
			Alpha2:       "AM",
			Alpha3:       "ARM",
			Numeric:      "051",
			DialingCodes: []string{"+374"},
			Name:         "Armenia",
		},
		Currencies: []string{"AMD"},
		Languages:  []string{"hye", "rus"},
	},
	"AGO": country{
		Country: Country{
			Alpha2:       "AO",
			Alpha3:       "AGO",
			Numeric:      "024",
			DialingCodes: []string{"+244"},
			Name:         "Angola",
		},
		Currencies: []string{"AOA"},
		Languages:  []string{"por"},
	},
	"ARG": country{
		Country: Country{
			Alpha2:       "AR",
			Alpha3:       "ARG",
			Numeric:      "032",
			DialingCodes: []string{"+54"},
			Name:         "Argentina",
		},
		Currencies: []string{"ARS"},
		Languages:  []string{"spa"},
	},
	"ASM": country{
		Country: Country{
			Alpha2:       "AS",
			Alpha3:       "ASM",
			Numeric:      "016",
			DialingCodes: []string{"+1 684"},
			Name:         "American Samoa",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng", "smo"},
	},
	"AUT": country{
		Country: Country{
			Alpha2:       "AT",
			Alpha3:       "AUT",
			Numeric:      "040",
			DialingCodes: []string{"+43"},
			Name:         "Austria",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"deu"},
	},
	"AUS": country{
		Country: Country{
			Alpha2:       "AU",
			Alpha3:       "AUS",
			Numeric:      "036",
			DialingCodes: []string{"+61"},
			Name:         "Australia",
		},
		Currencies: []string{"AUD"},
		Languages:  []string{"eng"},
	},
	"ABW": country{
		Country: Country{
			Alpha2:       "AW",
			Alpha3:       "ABW",
			Numeric:      "533",
			DialingCodes: []string{"+297"},
			Name:         "Aruba",
		},
		Currencies: []string{"AWG"},
		Languages:  []string{"nld"},
	},
	"ALA": country{
		Country: Country{
			Alpha2:       "AX",
			Alpha3:       "ALA",
			Numeric:      "248",
			DialingCodes: []string{"+358"},
			Name:         "Åland Islands",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"swe"},
	},
	"AZE": country{
		Country: Country{
			Alpha2:       "AZ",
			Alpha3:       "AZE",
			Numeric:      "031",
			DialingCodes: []string{"+994"},
			Name:         "Azerbaijan",
		},
		Currencies: []string{"AZN"},
		Languages:  []string{"aze"},
	},
	"BIH": country{
		Country: Country{
			Alpha2:       "BA",
			Alpha3:       "BIH",
			Numeric:      "070",
			DialingCodes: []string{"+387"},
			Name:         "Bosnia & Herzegovina",
		},
		Currencies: []string{"BAM"},
		Languages:  []string{"bos", "cre", "srp"},
	},
	"BRB": country{
		Country: Country{
			Alpha2:       "BB",
			Alpha3:       "BRB",
			Numeric:      "052",
			DialingCodes: []string{"+1 246"},
			Name:         "Barbados",
		},
		Currencies: []string{"BBD"},
		Languages:  []string{"eng"},
	},
	"BGD": country{
		Country: Country{
			Alpha2:       "BD",
			Alpha3:       "BGD",
			Numeric:      "050",
			DialingCodes: []string{"+880"},
			Name:         "Bangladesh",
		},
		Currencies: []string{"BDT"},
		Languages:  []string{"ben"},
	},
	"BEL": country{
		Country: Country{
			Alpha2:       "BE",
			Alpha3:       "BEL",
			Numeric:      "056",
			DialingCodes: []string{"+32"},
			Name:         "Belgium",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"nld", "fra", "deu"},
	},
	"BFA": country{
		Country: Country{
			Alpha2:       "BF",
			Alpha3:       "BFA",
			Numeric:      "854",
			DialingCodes: []string{"+226"},
			Name:         "Burkina Faso",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"fra"},
	},
	"BGR": country{
		Country: Country{
			Alpha2:       "BG",
			Alpha3:       "BGR",
			Numeric:      "100",
			DialingCodes: []string{"+359"},
			Name:         "Bulgaria",
		},
		Currencies: []string{"BGN"},
		Languages:  []string{"bul"},
	},
	"BHR": country{
		Country: Country{
			Alpha2:       "BH",
			Alpha3:       "BHR",
			Numeric:      "048",
			DialingCodes: []string{"+973"},
			Name:         "Bahrain",
		},
		Currencies: []string{"BHD"},
		Languages:  []string{"ara"},
	},
	"BDI": country{
		Country: Country{
			Alpha2:       "BI",
			Alpha3:       "BDI",
			Numeric:      "108",
			DialingCodes: []string{"+257"},
			Name:         "Burundi",
		},
		Currencies: []string{"BIF"},
		Languages:  []string{"fra"},
	},
	"BEN": country{
		Country: Country{
			Alpha2:       "BJ",
			Alpha3:       "BEN",
			Numeric:      "204",
			DialingCodes: []string{"+229"},
			Name:         "Benin",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"fra"},
	},
	"BLM": country{
		Country: Country{
			Alpha2:       "BL",
			Alpha3:       "BLM",
			Numeric:      "652",
			DialingCodes: []string{"+590"},
			Name:         "Saint Barthélemy",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"BMU": country{
		Country: Country{
			Alpha2:       "BM",
			Alpha3:       "BMU",
			Numeric:      "060",
			DialingCodes: []string{"+1 441"},
			Name:         "Bermuda",
		},
		Currencies: []string{"BMD"},
		Languages:  []string{"eng"},
	},
	"BRN": country{
		Country: Country{
			Alpha2:       "BN",
			Alpha3:       "BRN",
			Numeric:      "096",
			DialingCodes: []string{"+673"},
			Name:         "Brunei Darussalam",
		},
		Currencies: []string{"BND"},
		Languages:  []string{"msa", "eng"},
	},
	"BOL": country{
		Country: Country{
			Alpha2:       "BO",
			Alpha3:       "BOL",
			Numeric:      "068",
			DialingCodes: []string{"+591"},
			Name:         "Bolivia, Plurinational State Of",
		},
		Currencies: []string{"BOB", "BOV"},
		Languages:  []string{"spa", "aym", "que"},
	},
	"BES": country{
		Country: Country{
			Alpha2:       "BQ",
			Alpha3:       "BES",
			Numeric:      "535",
			DialingCodes: []string{"+599"},
			Name:         "Bonaire, Saint Eustatius And Saba",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"nld"},
	},
	"BRA": country{
		Country: Country{
			Alpha2:       "BR",
			Alpha3:       "BRA",
			Numeric:      "076",
			DialingCodes: []string{"+55"},
			Name:         "Brazil",
		},
		Currencies: []string{"BRL"},
		Languages:  []string{"por"},
	},
	"BHS": country{
		Country: Country{
			Alpha2:       "BS",
			Alpha3:       "BHS",
			Numeric:      "044",
			DialingCodes: []string{"+1 242"},
			Name:         "Bahamas",
		},
		Currencies: []string{"BSD"},
		Languages:  []string{"eng"},
	},
	"BTN": country{
		Country: Country{
			Alpha2:       "BT",
			Alpha3:       "BTN",
			Numeric:      "064",
			DialingCodes: []string{"+975"},
			Name:         "Bhutan",
		},
		Currencies: []string{"INR", "BTN"},
		Languages:  []string{"dzo"},
	},
	"BWA": country{
		Country: Country{
			Alpha2:       "BW",
			Alpha3:       "BWA",
			Numeric:      "072",
			DialingCodes: []string{"+267"},
			Name:         "Botswana",
		},
		Currencies: []string{"BWP"},
		Languages:  []string{"eng", "tsn"},
	},
	"BLR": country{
		Country: Country{
			Alpha2:       "BY",
			Alpha3:       "BLR",
			Numeric:      "112",
			DialingCodes: []string{"+375"},
			Name:         "Belarus",
		},
		Currencies: []string{"BYR"},
		Languages:  []string{"bel", "rus"},
	},
	"BLZ": country{
		Country: Country{
			Alpha2:       "BZ",
			Alpha3:       "BLZ",
			Numeric:      "084",
			DialingCodes: []string{"+501"},
			Name:         "Belize",
		},
		Currencies: []string{"BZD"},
		Languages:  []string{"eng"},
	},
	"CAN": country{
		Country: Country{
			Alpha2:       "CA",
			Alpha3:       "CAN",
			Numeric:      "124",
			DialingCodes: []string{"+1"},
			Name:         "Canada",
		},
		Currencies: []string{"CAD"},
		Languages:  []string{"eng", "fra"},
	},
	"CCK": country{
		Country: Country{
			Alpha2:       "CC",
			Alpha3:       "CCK",
			Numeric:      "166",
			DialingCodes: []string{"+61"},
			Name:         "Cocos (Keeling) Islands",
		},
		Currencies: []string{"AUD"},
		Languages:  []string{"eng"},
	},
	"COD": country{
		Country: Country{
			Alpha2:       "CD",
			Alpha3:       "COD",
			Numeric:      "180",
			DialingCodes: []string{"+243"},
			Name:         "Democratic Republic Of Congo",
		},
		Currencies: []string{"CDF"},
		Languages:  []string{"fra", "lin", "kon", "swa"},
	},
	"CAF": country{
		Country: Country{
			Alpha2:       "CF",
			Alpha3:       "CAF",
			Numeric:      "140",
			DialingCodes: []string{"+236"},
			Name:         "Central African Republic",
		},
		Currencies: []string{"XAF"},
		Languages:  []string{"fra", "sag"},
	},
	"COG": country{
		Country: Country{
			Alpha2:       "CG",
			Alpha3:       "COG",
			Numeric:      "178",
			DialingCodes: []string{"+242"},
			Name:         "Republic Of Congo",
		},
		Currencies: []string{"XAF"},
		Languages:  []string{"fra", "lin"},
	},
	"CHE": country{
		Country: Country{
			Alpha2:       "CH",
			Alpha3:       "CHE",
			Numeric:      "756",
			DialingCodes: []string{"+41"},
			Name:         "Switzerland",
		},
		Currencies: []string{"CHF", "CHE", "CHW"},
		Languages:  []string{"deu", "fra", "ita", "roh"},
	},
	"CIV": country{
		Country: Country{
			Alpha2:       "CI",
			Alpha3:       "CIV",
			Numeric:      "384",
			DialingCodes: []string{"+225"},
			Name:         "Côte d'Ivoire",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"fra"},
	},
	"COK": country{
		Country: Country{
			Alpha2:       "CK",
			Alpha3:       "COK",
			Numeric:      "184",
			DialingCodes: []string{"+682"},
			Name:         "Cook Islands",
		},
		Currencies: []string{"NZD"},
		Languages:  []string{"eng", "mri"},
	},
	"CHL": country{
		Country: Country{
			Alpha2:       "CL",
			Alpha3:       "CHL",
			Numeric:      "152",
			DialingCodes: []string{"+56"},
			Name:         "Chile",
		},
		Currencies: []string{"CLP", "CLF"},
		Languages:  []string{"spa"},
	},
	"CMR": country{
		Country: Country{
			Alpha2:       "CM",
			Alpha3:       "CMR",
			Numeric:      "120",
			DialingCodes: []string{"+237"},
			Name:         "Cameroon",
		},
		Currencies: []string{"XAF"},
		Languages:  []string{"eng", "fra"},
	},
	"CHN": country{
		Country: Country{
			Alpha2:       "CN",
			Alpha3:       "CHN",
			Numeric:      "156",
			DialingCodes: []string{"+86"},
			Name:         "China",
		},
		Currencies: []string{"CNY"},
		Languages:  []string{"zho"},
	},
	"COL": country{
		Country: Country{
			Alpha2:       "CO",
			Alpha3:       "COL",
			Numeric:      "170",
			DialingCodes: []string{"+57"},
			Name:         "Colombia",
		},
		Currencies: []string{"COP", "COU"},
		Languages:  []string{"spa"},
	},
	"CRI": country{
		Country: Country{
			Alpha2:       "CR",
			Alpha3:       "CRI",
			Numeric:      "188",
			DialingCodes: []string{"+506"},
			Name:         "Costa Rica",
		},
		Currencies: []string{"CRC"},
		Languages:  []string{"spa"},
	},
	"CUB": country{
		Country: Country{
			Alpha2:       "CU",
			Alpha3:       "CUB",
			Numeric:      "192",
			DialingCodes: []string{"+53"},
			Name:         "Cuba",
		},
		Currencies: []string{"CUP", "CUC"},
		Languages:  []string{"spa"},
	},
	"CPV": country{
		Country: Country{
			Alpha2:       "CV",
			Alpha3:       "CPV",
			Numeric:      "132",
			DialingCodes: []string{"+238"},
			Name:         "Cabo Verde",
		},
		Currencies: []string{"CVE"},
		Languages:  []string{"por"},
	},
	"CUW": country{
		Country: Country{
			Alpha2:       "CW",
			Alpha3:       "CUW",
			Numeric:      "531",
			DialingCodes: []string{"+599"},
			Name:         "Curacao",
		},
		Currencies: []string{"ANG"},
		Languages:  []string{"nld"},
	},
	"CXR": country{
		Country: Country{
			Alpha2:       "CX",
			Alpha3:       "CXR",
			Numeric:      "162",
			DialingCodes: []string{"+61"},
			Name:         "Christmas Island",
		},
		Currencies: []string{"AUD"},
		Languages:  []string{"eng"},
	},
	"CYP": country{
		Country: Country{
			Alpha2:       "CY",
			Alpha3:       "CYP",
			Numeric:      "196",
			DialingCodes: []string{"+357"},
			Name:         "Cyprus",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"ell", "tur"},
	},
	"CZE": country{
		Country: Country{
			Alpha2:       "CZ",
			Alpha3:       "CZE",
			Numeric:      "203",
			DialingCodes: []string{"+420"},
			Name:         "Czech Republic",
		},
		Currencies: []string{"CZK"},
		Languages:  []string{"ces"},
	},
	"DEU": country{
		Country: Country{
			Alpha2:       "DE",
			Alpha3:       "DEU",
			Numeric:      "276",
			DialingCodes: []string{"+49"},
			Name:         "Germany",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"deu"},
	},
	"DJI": country{
		Country: Country{
			Alpha2:       "DJ",
			Alpha3:       "DJI",
			Numeric:      "262",
			DialingCodes: []string{"+253"},
			Name:         "Djibouti",
		},
		Currencies: []string{"DJF"},
		Languages:  []string{"ara", "fra"},
	},
	"DNK": country{
		Country: Country{
			Alpha2:       "DK",
			Alpha3:       "DNK",
			Numeric:      "208",
			DialingCodes: []string{"+45"},
			Name:         "Denmark",
		},
		Currencies: []string{"DKK"},
		Languages:  []string{"dan"},
	},
	"DMA": country{
		Country: Country{
			Alpha2:       "DM",
			Alpha3:       "DMA",
			Numeric:      "212",
			DialingCodes: []string{"+1 767"},
			Name:         "Dominica",
		},
		Currencies: []string{"XCD"},
		Languages:  []string{"eng"},
	},
	"DOM": country{
		Country: Country{
			Alpha2:       "DO",
			Alpha3:       "DOM",
			Numeric:      "214",
			DialingCodes: []string{"+1 809", "+1 829", "+1 849"},
			Name:         "Dominican Republic",
		},
		Currencies: []string{"DOP"},
		Languages:  []string{"spa"},
	},
	"DZA": country{
		Country: Country{
			Alpha2:       "DZ",
			Alpha3:       "DZA",
			Numeric:      "012",
			DialingCodes: []string{"+213"},
			Name:         "Algeria",
		},
		Currencies: []string{"DZD"},
		Languages:  []string{"ara"},
	},
	"ECU": country{
		Country: Country{
			Alpha2:       "EC",
			Alpha3:       "ECU",
			Numeric:      "218",
			DialingCodes: []string{"+593"},
			Name:         "Ecuador",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"spa", "que"},
	},
	"EST": country{
		Country: Country{
			Alpha2:       "EE",
			Alpha3:       "EST",
			Numeric:      "233",
			DialingCodes: []string{"+372"},
			Name:         "Estonia",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"est"},
	},
	"EGY": country{
		Country: Country{
			Alpha2:       "EG",
			Alpha3:       "EGY",
			Numeric:      "818",
			DialingCodes: []string{"+20"},
			Name:         "Egypt",
		},
		Currencies: []string{"EGP"},
		Languages:  []string{"ara"},
	},
	"ERI": country{
		Country: Country{
			Alpha2:       "ER",
			Alpha3:       "ERI",
			Numeric:      "232",
			DialingCodes: []string{"+291"},
			Name:         "Eritrea",
		},
		Currencies: []string{"ERN"},
		Languages:  []string{"eng", "ara", "tir"},
	},
	"ESP": country{
		Country: Country{
			Alpha2:       "ES",
			Alpha3:       "ESP",
			Numeric:      "724",
			DialingCodes: []string{"+34"},
			Name:         "Spain",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"spa"},
	},
	"ETH": country{
		Country: Country{
			Alpha2:       "ET",
			Alpha3:       "ETH",
			Numeric:      "231",
			DialingCodes: []string{"+251"},
			Name:         "Ethiopia",
		},
		Currencies: []string{"ETB"},
		Languages:  []string{"amh"},
	},
	"FIN": country{
		Country: Country{
			Alpha2:       "FI",
			Alpha3:       "FIN",
			Numeric:      "246",
			DialingCodes: []string{"+358"},
			Name:         "Finland",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fin", "swe"},
	},
	"FJI": country{
		Country: Country{
			Alpha2:       "FJ",
			Alpha3:       "FJI",
			Numeric:      "242",
			DialingCodes: []string{"+679"},
			Name:         "Fiji",
		},
		Currencies: []string{"FJD"},
		Languages:  []string{"eng", "fij"},
	},
	"FLK": country{
		Country: Country{
			Alpha2:       "FK",
			Alpha3:       "FLK",
			Numeric:      "238",
			DialingCodes: []string{"+500"},
			Name:         "Falkland Islands",
		},
		Currencies: []string{"FKP"},
		Languages:  []string{"eng"},
	},
	"FSM": country{
		Country: Country{
			Alpha2:       "FM",
			Alpha3:       "FSM",
			Numeric:      "583",
			DialingCodes: []string{"+691"},
			Name:         "Micronesia, Federated States Of",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"FRO": country{
		Country: Country{
			Alpha2:       "FO",
			Alpha3:       "FRO",
			Numeric:      "234",
			DialingCodes: []string{"+298"},
			Name:         "Faroe Islands",
		},
		Currencies: []string{"DKK"},
		Languages:  []string{"fao", "dan"},
	},
	"FRA": country{
		Country: Country{
			Alpha2:       "FR",
			Alpha3:       "FRA",
			Numeric:      "250",
			DialingCodes: []string{"+33"},
			Name:         "France",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"GAB": country{
		Country: Country{
			Alpha2:       "GA",
			Alpha3:       "GAB",
			Numeric:      "266",
			DialingCodes: []string{"+241"},
			Name:         "Gabon",
		},
		Currencies: []string{"XAF"},
		Languages:  []string{"fra"},
	},
	"GBR": country{
		Country: Country{
			Alpha2:       "GB",
			Alpha3:       "GBR",
			Numeric:      "826",
			DialingCodes: []string{"+44"},
			Name:         "United Kingdom",
		},
		Currencies: []string{"GBP"},
		Languages:  []string{"eng", "cor", "gle", "gla", "cym"},
	},
	"GRD": country{
		Country: Country{
			Alpha2:       "GD",
			Alpha3:       "GRD",
			Numeric:      "308",
			DialingCodes: []string{"+473"},
			Name:         "Grenada",
		},
		Currencies: []string{"XCD"},
		Languages:  []string{"eng"},
	},
	"GEO": country{
		Country: Country{
			Alpha2:       "GE",
			Alpha3:       "GEO",
			Numeric:      "268",
			DialingCodes: []string{"+995"},
			Name:         "Georgia",
		},
		Currencies: []string{"GEL"},
		Languages:  []string{"kat"},
	},
	"GUF": country{
		Country: Country{
			Alpha2:       "GF",
			Alpha3:       "GUF",
			Numeric:      "254",
			DialingCodes: []string{"+594"},
			Name:         "French Guiana",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"GGY": country{
		Country: Country{
			Alpha2:       "GG",
			Alpha3:       "GGY",
			Numeric:      "831",
			DialingCodes: []string{"+44"},
			Name:         "Guernsey",
		},
		Currencies: []string{"GBP"},
		Languages:  []string{"fra"},
	},
	"GHA": country{
		Country: Country{
			Alpha2:       "GH",
			Alpha3:       "GHA",
			Numeric:      "288",
			DialingCodes: []string{"+233"},
			Name:         "Ghana",
		},
		Currencies: []string{"GHS"},
		Languages:  []string{"eng"},
	},
	"GIB": country{
		Country: Country{
			Alpha2:       "GI",
			Alpha3:       "GIB",
			Numeric:      "292",
			DialingCodes: []string{"+350"},
			Name:         "Gibraltar",
		},
		Currencies: []string{"GIP"},
		Languages:  []string{"eng"},
	},
	"GRL": country{
		Country: Country{
			Alpha2:       "GL",
			Alpha3:       "GRL",
			Numeric:      "304",
			DialingCodes: []string{"+299"},
			Name:         "Greenland",
		},
		Currencies: []string{"DKK"},
		Languages:  []string{"kal"},
	},
	"GMB": country{
		Country: Country{
			Alpha2:       "GM",
			Alpha3:       "GMB",
			Numeric:      "270",
			DialingCodes: []string{"+220"},
			Name:         "Gambia",
		},
		Currencies: []string{"GMD"},
		Languages:  []string{"eng"},
	},
	"GIN": country{
		Country: Country{
			Alpha2:       "GN",
			Alpha3:       "GIN",
			Numeric:      "324",
			DialingCodes: []string{"+224"},
			Name:         "Guinea",
		},
		Currencies: []string{"GNF"},
		Languages:  []string{"fra"},
	},
	"GLP": country{
		Country: Country{
			Alpha2:       "GP",
			Alpha3:       "GLP",
			Numeric:      "312",
			DialingCodes: []string{"+590"},
			Name:         "Guadeloupe",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"GNQ": country{
		Country: Country{
			Alpha2:       "GQ",
			Alpha3:       "GNQ",
			Numeric:      "226",
			DialingCodes: []string{"+240"},
			Name:         "Equatorial Guinea",
		},
		Currencies: []string{"XAF"},
		Languages:  []string{"spa", "fra", "por"},
	},
	"GRC": country{
		Country: Country{
			Alpha2:       "GR",
			Alpha3:       "GRC",
			Numeric:      "300",
			DialingCodes: []string{"+30"},
			Name:         "Greece",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"ell"},
	},
	"SGS": country{
		Country: Country{
			Alpha2:       "GS",
			Alpha3:       "SGS",
			Numeric:      "239",
			DialingCodes: []string{},
			Name:         "South Georgia And The South Sandwich Islands",
		},
		Currencies: []string{"GBP"},
		Languages:  []string{"eng"},
	},
	"GTM": country{
		Country: Country{
			Alpha2:       "GT",
			Alpha3:       "GTM",
			Numeric:      "320",
			DialingCodes: []string{"+502"},
			Name:         "Guatemala",
		},
		Currencies: []string{"GTQ"},
		Languages:  []string{"spa"},
	},
	"GUM": country{
		Country: Country{
			Alpha2:       "GU",
			Alpha3:       "GUM",
			Numeric:      "316",
			DialingCodes: []string{"+1 671"},
			Name:         "Guam",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"GNB": country{
		Country: Country{
			Alpha2:       "GW",
			Alpha3:       "GNB",
			Numeric:      "624",
			DialingCodes: []string{"+245"},
			Name:         "Guinea-bissau",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"por"},
	},
	"GUY": country{
		Country: Country{
			Alpha2:       "GY",
			Alpha3:       "GUY",
			Numeric:      "328",
			DialingCodes: []string{"+592"},
			Name:         "Guyana",
		},
		Currencies: []string{"GYD"},
		Languages:  []string{"eng"},
	},
	"HKG": country{
		Country: Country{
			Alpha2:       "HK",
			Alpha3:       "HKG",
			Numeric:      "344",
			DialingCodes: []string{"+852"},
			Name:         "Hong Kong",
		},
		Currencies: []string{"HKD"},
		Languages:  []string{"zho", "eng"},
	},
	"HND": country{
		Country: Country{
			Alpha2:       "HN",
			Alpha3:       "HND",
			Numeric:      "340",
			DialingCodes: []string{"+504"},
			Name:         "Honduras",
		},
		Currencies: []string{"HNL"},
		Languages:  []string{"spa"},
	},
	"HRV": country{
		Country: Country{
			Alpha2:       "HR",
			Alpha3:       "HRV",
			Numeric:      "191",
			DialingCodes: []string{"+385"},
			Name:         "Croatia",
		},
		Currencies: []string{"HRK"},
		Languages:  []string{"hrv"},
	},
	"HTI": country{
		Country: Country{
			Alpha2:       "HT",
			Alpha3:       "HTI",
			Numeric:      "332",
			DialingCodes: []string{"+509"},
			Name:         "Haiti",
		},
		Currencies: []string{"HTG", "USD"},
		Languages:  []string{"fra", "hat"},
	},
	"HUN": country{
		Country: Country{
			Alpha2:       "HU",
			Alpha3:       "HUN",
			Numeric:      "348",
			DialingCodes: []string{"+36"},
			Name:         "Hungary",
		},
		Currencies: []string{"HUF"},
		Languages:  []string{"hun"},
	},
	"IDN": country{
		Country: Country{
			Alpha2:       "ID",
			Alpha3:       "IDN",
			Numeric:      "360",
			DialingCodes: []string{"+62"},
			Name:         "Indonesia",
		},
		Currencies: []string{"IDR"},
		Languages:  []string{"ind"},
	},
	"IRL": country{
		Country: Country{
			Alpha2:       "IE",
			Alpha3:       "IRL",
			Numeric:      "372",
			DialingCodes: []string{"+353"},
			Name:         "Ireland",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"eng", "gle"},
	},
	"ISR": country{
		Country: Country{
			Alpha2:       "IL",
			Alpha3:       "ISR",
			Numeric:      "376",
			DialingCodes: []string{"+972"},
			Name:         "Israel",
		},
		Currencies: []string{"ILS"},
		Languages:  []string{"heb", "ara", "eng"},
	},
	"IMN": country{
		Country: Country{
			Alpha2:       "IM",
			Alpha3:       "IMN",
			Numeric:      "833",
			DialingCodes: []string{"+44"},
			Name:         "Isle Of Man",
		},
		Currencies: []string{"GBP"},
		Languages:  []string{"eng", "glv"},
	},
	"IND": country{
		Country: Country{
			Alpha2:       "IN",
			Alpha3:       "IND",
			Numeric:      "356",
			DialingCodes: []string{"+91"},
			Name:         "India",
		},
		Currencies: []string{"INR"},
		Languages:  []string{"eng", "hin"},
	},
	"IOT": country{
		Country: Country{
			Alpha2:       "IO",
			Alpha3:       "IOT",
			Numeric:      "086",
			DialingCodes: []string{"+246"},
			Name:         "British Indian Ocean Territory",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"IRQ": country{
		Country: Country{
			Alpha2:       "IQ",
			Alpha3:       "IRQ",
			Numeric:      "368",
			DialingCodes: []string{"+964"},
			Name:         "Iraq",
		},
		Currencies: []string{"IQD"},
		Languages:  []string{"ara", "kur"},
	},
	"IRN": country{
		Country: Country{
			Alpha2:       "IR",
			Alpha3:       "IRN",
			Numeric:      "364",
			DialingCodes: []string{"+98"},
			Name:         "Iran, Islamic Republic Of",
		},
		Currencies: []string{"IRR"},
		Languages:  []string{"fas"},
	},
	"ISL": country{
		Country: Country{
			Alpha2:       "IS",
			Alpha3:       "ISL",
			Numeric:      "352",
			DialingCodes: []string{"+354"},
			Name:         "Iceland",
		},
		Currencies: []string{"ISK"},
		Languages:  []string{"isl"},
	},
	"ITA": country{
		Country: Country{
			Alpha2:       "IT",
			Alpha3:       "ITA",
			Numeric:      "380",
			DialingCodes: []string{"+39"},
			Name:         "Italy",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"ita"},
	},
	"JEY": country{
		Country: Country{
			Alpha2:       "JE",
			Alpha3:       "JEY",
			Numeric:      "832",
			DialingCodes: []string{"+44"},
			Name:         "Jersey",
		},
		Currencies: []string{"GBP"},
		Languages:  []string{"eng", "fra"},
	},
	"JAM": country{
		Country: Country{
			Alpha2:       "JM",
			Alpha3:       "JAM",
			Numeric:      "388",
			DialingCodes: []string{"+1 876"},
			Name:         "Jamaica",
		},
		Currencies: []string{"JMD"},
		Languages:  []string{"eng"},
	},
	"JOR": country{
		Country: Country{
			Alpha2:       "JO",
			Alpha3:       "JOR",
			Numeric:      "400",
			DialingCodes: []string{"+962"},
			Name:         "Jordan",
		},
		Currencies: []string{"JOD"},
		Languages:  []string{"ara"},
	},
	"JPN": country{
		Country: Country{
			Alpha2:       "JP",
			Alpha3:       "JPN",
			Numeric:      "392",
			DialingCodes: []string{"+81"},
			Name:         "Japan",
		},
		Currencies: []string{"JPY"},
		Languages:  []string{"jpn"},
	},
	"KEN": country{
		Country: Country{
			Alpha2:       "KE",
			Alpha3:       "KEN",
			Numeric:      "404",
			DialingCodes: []string{"+254"},
			Name:         "Kenya",
		},
		Currencies: []string{"KES"},
		Languages:  []string{"eng", "swa"},
	},
	"KGZ": country{
		Country: Country{
			Alpha2:       "KG",
			Alpha3:       "KGZ",
			Numeric:      "417",
			DialingCodes: []string{"+996"},
			Name:         "Kyrgyzstan",
		},
		Currencies: []string{"KGS"},
		Languages:  []string{"rus"},
	},
	"KHM": country{
		Country: Country{
			Alpha2:       "KH",
			Alpha3:       "KHM",
			Numeric:      "116",
			DialingCodes: []string{"+855"},
			Name:         "Cambodia",
		},
		Currencies: []string{"KHR"},
		Languages:  []string{"khm"},
	},
	"KIR": country{
		Country: Country{
			Alpha2:       "KI",
			Alpha3:       "KIR",
			Numeric:      "296",
			DialingCodes: []string{"+686"},
			Name:         "Kiribati",
		},
		Currencies: []string{"AUD"},
		Languages:  []string{"eng"},
	},
	"COM": country{
		Country: Country{
			Alpha2:       "KM",
			Alpha3:       "COM",
			Numeric:      "174",
			DialingCodes: []string{"+269"},
			Name:         "Comoros",
		},
		Currencies: []string{"KMF"},
		Languages:  []string{"ara", "fra"},
	},
	"KNA": country{
		Country: Country{
			Alpha2:       "KN",
			Alpha3:       "KNA",
			Numeric:      "659",
			DialingCodes: []string{"+1 869"},
			Name:         "Saint Kitts And Nevis",
		},
		Currencies: []string{"XCD"},
		Languages:  []string{"eng"},
	},
	"PRK": country{
		Country: Country{
			Alpha2:       "KP",
			Alpha3:       "PRK",
			Numeric:      "408",
			DialingCodes: []string{"+850"},
			Name:         "Korea, Democratic People's Republic Of",
		},
		Currencies: []string{"KPW"},
		Languages:  []string{"kor"},
	},
	"KOR": country{
		Country: Country{
			Alpha2:       "KR",
			Alpha3:       "KOR",
			Numeric:      "410",
			DialingCodes: []string{"+82"},
			Name:         "Korea, Republic Of",
		},
		Currencies: []string{"KRW"},
		Languages:  []string{"kor"},
	},
	"KWT": country{
		Country: Country{
			Alpha2:       "KW",
			Alpha3:       "KWT",
			Numeric:      "414",
			DialingCodes: []string{"+965"},
			Name:         "Kuwait",
		},
		Currencies: []string{"KWD"},
		Languages:  []string{"ara"},
	},
	"CYM": country{
		Country: Country{
			Alpha2:       "KY",
			Alpha3:       "CYM",
			Numeric:      "136",
			DialingCodes: []string{"+1 345"},
			Name:         "Cayman Islands",
		},
		Currencies: []string{"KYD"},
		Languages:  []string{"eng"},
	},
	"KAZ": country{
		Country: Country{
			Alpha2:       "KZ",
			Alpha3:       "KAZ",
			Numeric:      "398",
			DialingCodes: []string{"+7", "+7 6", "+7 7"},
			Name:         "Kazakhstan",
		},
		Currencies: []string{"KZT"},
		Languages:  []string{"kaz", "rus"},
	},
	"LAO": country{
		Country: Country{
			Alpha2:       "LA",
			Alpha3:       "LAO",
			Numeric:      "418",
			DialingCodes: []string{"+856"},
			Name:         "Lao People's Democratic Republic",
		},
		Currencies: []string{"LAK"},
		Languages:  []string{"lao"},
	},
	"LBN": country{
		Country: Country{
			Alpha2:       "LB",
			Alpha3:       "LBN",
			Numeric:      "422",
			DialingCodes: []string{"+961"},
			Name:         "Lebanon",
		},
		Currencies: []string{"LBP"},
		Languages:  []string{"ara", "hye"},
	},
	"LCA": country{
		Country: Country{
			Alpha2:       "LC",
			Alpha3:       "LCA",
			Numeric:      "662",
			DialingCodes: []string{"+1 758"},
			Name:         "Saint Lucia",
		},
		Currencies: []string{"XCD"},
		Languages:  []string{"eng"},
	},
	"LIE": country{
		Country: Country{
			Alpha2:       "LI",
			Alpha3:       "LIE",
			Numeric:      "438",
			DialingCodes: []string{"+423"},
			Name:         "Liechtenstein",
		},
		Currencies: []string{"CHF"},
		Languages:  []string{"deu"},
	},
	"LKA": country{
		Country: Country{
			Alpha2:       "LK",
			Alpha3:       "LKA",
			Numeric:      "144",
			DialingCodes: []string{"+94"},
			Name:         "Sri Lanka",
		},
		Currencies: []string{"LKR"},
		Languages:  []string{"sin", "tam"},
	},
	"LBR": country{
		Country: Country{
			Alpha2:       "LR",
			Alpha3:       "LBR",
			Numeric:      "430",
			DialingCodes: []string{"+231"},
			Name:         "Liberia",
		},
		Currencies: []string{"LRD"},
		Languages:  []string{"eng"},
	},
	"LSO": country{
		Country: Country{
			Alpha2:       "LS",
			Alpha3:       "LSO",
			Numeric:      "426",
			DialingCodes: []string{"+266"},
			Name:         "Lesotho",
		},
		Currencies: []string{"LSL", "ZAR"},
		Languages:  []string{"eng", "sot"},
	},
	"LTU": country{
		Country: Country{
			Alpha2:       "LT",
			Alpha3:       "LTU",
			Numeric:      "440",
			DialingCodes: []string{"+370"},
			Name:         "Lithuania",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"lit"},
	},
	"LUX": country{
		Country: Country{
			Alpha2:       "LU",
			Alpha3:       "LUX",
			Numeric:      "442",
			DialingCodes: []string{"+352"},
			Name:         "Luxembourg",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra", "deu", "ltz"},
	},
	"LVA": country{
		Country: Country{
			Alpha2:       "LV",
			Alpha3:       "LVA",
			Numeric:      "428",
			DialingCodes: []string{"+371"},
			Name:         "Latvia",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"lav"},
	},
	"LBY": country{
		Country: Country{
			Alpha2:       "LY",
			Alpha3:       "LBY",
			Numeric:      "434",
			DialingCodes: []string{"+218"},
			Name:         "Libya",
		},
		Currencies: []string{"LYD"},
		Languages:  []string{"ara"},
	},
	"MAR": country{
		Country: Country{
			Alpha2:       "MA",
			Alpha3:       "MAR",
			Numeric:      "504",
			DialingCodes: []string{"+212"},
			Name:         "Morocco",
		},
		Currencies: []string{"MAD"},
		Languages:  []string{"ara"},
	},
	"MCO": country{
		Country: Country{
			Alpha2:       "MC",
			Alpha3:       "MCO",
			Numeric:      "492",
			DialingCodes: []string{"+377"},
			Name:         "Monaco",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"MDA": country{
		Country: Country{
			Alpha2:       "MD",
			Alpha3:       "MDA",
			Numeric:      "498",
			DialingCodes: []string{"+373"},
			Name:         "Moldova",
		},
		Currencies: []string{"MDL"},
		Languages:  []string{"ron"},
	},
	"MNE": country{
		Country: Country{
			Alpha2:       "ME",
			Alpha3:       "MNE",
			Numeric:      "499",
			DialingCodes: []string{"+382"},
			Name:         "Montenegro",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"mot"},
	},
	"MAF": country{
		Country: Country{
			Alpha2:       "MF",
			Alpha3:       "MAF",
			Numeric:      "663",
			DialingCodes: []string{"+590"},
			Name:         "Saint Martin",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"MDG": country{
		Country: Country{
			Alpha2:       "MG",
			Alpha3:       "MDG",
			Numeric:      "450",
			DialingCodes: []string{"+261"},
			Name:         "Madagascar",
		},
		Currencies: []string{"MGA"},
		Languages:  []string{"fra", "mlg"},
	},
	"MHL": country{
		Country: Country{
			Alpha2:       "MH",
			Alpha3:       "MHL",
			Numeric:      "584",
			DialingCodes: []string{"+692"},
			Name:         "Marshall Islands",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng", "mah"},
	},
	"MKD": country{
		Country: Country{
			Alpha2:       "MK",
			Alpha3:       "MKD",
			Numeric:      "807",
			DialingCodes: []string{"+389"},
			Name:         "Macedonia, The Former Yugoslav Republic Of",
		},
		Currencies: []string{"MKD"},
		Languages:  []string{"mkd"},
	},
	"MLI": country{
		Country: Country{
			Alpha2:       "ML",
			Alpha3:       "MLI",
			Numeric:      "466",
			DialingCodes: []string{"+223"},
			Name:         "Mali",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"fra"},
	},
	"MMR": country{
		Country: Country{
			Alpha2:       "MM",
			Alpha3:       "MMR",
			Numeric:      "104",
			DialingCodes: []string{"+95"},
			Name:         "Myanmar",
		},
		Currencies: []string{"MMK"},
		Languages:  []string{"mya"},
	},
	"MNG": country{
		Country: Country{
			Alpha2:       "MN",
			Alpha3:       "MNG",
			Numeric:      "496",
			DialingCodes: []string{"+976"},
			Name:         "Mongolia",
		},
		Currencies: []string{"MNT"},
		Languages:  []string{"mon"},
	},
	"MAC": country{
		Country: Country{
			Alpha2:       "MO",
			Alpha3:       "MAC",
			Numeric:      "446",
			DialingCodes: []string{"+853"},
			Name:         "Macao",
		},
		Currencies: []string{"MOP"},
		Languages:  []string{"zho", "por"},
	},
	"MNP": country{
		Country: Country{
			Alpha2:       "MP",
			Alpha3:       "MNP",
			Numeric:      "580",
			DialingCodes: []string{"+1 670"},
			Name:         "Northern Mariana Islands",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"MRT": country{
		Country: Country{
			Alpha2:       "MR",
			Alpha3:       "MRT",
			Numeric:      "478",
			DialingCodes: []string{"+222"},
			Name:         "Mauritania",
		},
		Currencies: []string{"MRO"},
		Languages:  []string{"ara", "fra"},
	},
	"MLT": country{
		Country: Country{
			Alpha2:       "MT",
			Alpha3:       "MLT",
			Numeric:      "470",
			DialingCodes: []string{"+356"},
			Name:         "Malta",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"mlt", "eng"},
	},
	"MUS": country{
		Country: Country{
			Alpha2:       "MU",
			Alpha3:       "MUS",
			Numeric:      "480",
			DialingCodes: []string{"+230"},
			Name:         "Mauritius",
		},
		Currencies: []string{"MUR"},
		Languages:  []string{"eng", "fra"},
	},
	"MDV": country{
		Country: Country{
			Alpha2:       "MV",
			Alpha3:       "MDV",
			Numeric:      "462",
			DialingCodes: []string{"+960"},
			Name:         "Maldives",
		},
		Currencies: []string{"MVR"},
		Languages:  []string{"div"},
	},
	"MWI": country{
		Country: Country{
			Alpha2:       "MW",
			Alpha3:       "MWI",
			Numeric:      "454",
			DialingCodes: []string{"+265"},
			Name:         "Malawi",
		},
		Currencies: []string{"MWK"},
		Languages:  []string{"eng", "nya"},
	},
	"MEX": country{
		Country: Country{
			Alpha2:       "MX",
			Alpha3:       "MEX",
			Numeric:      "484",
			DialingCodes: []string{"+52"},
			Name:         "Mexico",
		},
		Currencies: []string{"MXN", "MXV"},
		Languages:  []string{"spa"},
	},
	"MYS": country{
		Country: Country{
			Alpha2:       "MY",
			Alpha3:       "MYS",
			Numeric:      "458",
			DialingCodes: []string{"+60"},
			Name:         "Malaysia",
		},
		Currencies: []string{"MYR"},
		Languages:  []string{"msa", "eng"},
	},
	"MOZ": country{
		Country: Country{
			Alpha2:       "MZ",
			Alpha3:       "MOZ",
			Numeric:      "508",
			DialingCodes: []string{"+258"},
			Name:         "Mozambique",
		},
		Currencies: []string{"MZN"},
		Languages:  []string{"por"},
	},
	"NAM": country{
		Country: Country{
			Alpha2:       "NA",
			Alpha3:       "NAM",
			Numeric:      "516",
			DialingCodes: []string{"+264"},
			Name:         "Namibia",
		},
		Currencies: []string{"NAD", "ZAR"},
		Languages:  []string{"eng"},
	},
	"NCL": country{
		Country: Country{
			Alpha2:       "NC",
			Alpha3:       "NCL",
			Numeric:      "540",
			DialingCodes: []string{"+687"},
			Name:         "New Caledonia",
		},
		Currencies: []string{"XPF"},
		Languages:  []string{"fra"},
	},
	"NER": country{
		Country: Country{
			Alpha2:       "NE",
			Alpha3:       "NER",
			Numeric:      "562",
			DialingCodes: []string{"+227"},
			Name:         "Niger",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"fra"},
	},
	"NFK": country{
		Country: Country{
			Alpha2:       "NF",
			Alpha3:       "NFK",
			Numeric:      "574",
			DialingCodes: []string{"+672"},
			Name:         "Norfolk Island",
		},
		Currencies: []string{"AUD"},
		Languages:  []string{"eng"},
	},
	"NGA": country{
		Country: Country{
			Alpha2:       "NG",
			Alpha3:       "NGA",
			Numeric:      "566",
			DialingCodes: []string{"+234"},
			Name:         "Nigeria",
		},
		Currencies: []string{"NGN"},
		Languages:  []string{"eng"},
	},
	"NIC": country{
		Country: Country{
			Alpha2:       "NI",
			Alpha3:       "NIC",
			Numeric:      "558",
			DialingCodes: []string{"+505"},
			Name:         "Nicaragua",
		},
		Currencies: []string{"NIO"},
		Languages:  []string{"spa"},
	},
	"NLD": country{
		Country: Country{
			Alpha2:       "NL",
			Alpha3:       "NLD",
			Numeric:      "528",
			DialingCodes: []string{"+31"},
			Name:         "Netherlands",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"nld"},
	},
	"NOR": country{
		Country: Country{
			Alpha2:       "NO",
			Alpha3:       "NOR",
			Numeric:      "578",
			DialingCodes: []string{"+47"},
			Name:         "Norway",
		},
		Currencies: []string{"NOK"},
		Languages:  []string{"nor"},
	},
	"NPL": country{
		Country: Country{
			Alpha2:       "NP",
			Alpha3:       "NPL",
			Numeric:      "524",
			DialingCodes: []string{"+977"},
			Name:         "Nepal",
		},
		Currencies: []string{"NPR"},
		Languages:  []string{"nep"},
	},
	"NRU": country{
		Country: Country{
			Alpha2:       "NR",
			Alpha3:       "NRU",
			Numeric:      "520",
			DialingCodes: []string{"+674"},
			Name:         "Nauru",
		},
		Currencies: []string{"AUD"},
		Languages:  []string{"eng", "nau"},
	},
	"NIU": country{
		Country: Country{
			Alpha2:       "NU",
			Alpha3:       "NIU",
			Numeric:      "570",
			DialingCodes: []string{"+683"},
			Name:         "Niue",
		},
		Currencies: []string{"NZD"},
		Languages:  []string{"eng"},
	},
	"NZL": country{
		Country: Country{
			Alpha2:       "NZ",
			Alpha3:       "NZL",
			Numeric:      "554",
			DialingCodes: []string{"+64"},
			Name:         "New Zealand",
		},
		Currencies: []string{"NZD"},
		Languages:  []string{"eng"},
	},
	"OMN": country{
		Country: Country{
			Alpha2:       "OM",
			Alpha3:       "OMN",
			Numeric:      "512",
			DialingCodes: []string{"+968"},
			Name:         "Oman",
		},
		Currencies: []string{"OMR"},
		Languages:  []string{"ara"},
	},
	"PAN": country{
		Country: Country{
			Alpha2:       "PA",
			Alpha3:       "PAN",
			Numeric:      "591",
			DialingCodes: []string{"+507"},
			Name:         "Panama",
		},
		Currencies: []string{"PAB", "USD"},
		Languages:  []string{"spa"},
	},
	"PER": country{
		Country: Country{
			Alpha2:       "PE",
			Alpha3:       "PER",
			Numeric:      "604",
			DialingCodes: []string{"+51"},
			Name:         "Peru",
		},
		Currencies: []string{"PEN"},
		Languages:  []string{"spa", "aym", "que"},
	},
	"PYF": country{
		Country: Country{
			Alpha2:       "PF",
			Alpha3:       "PYF",
			Numeric:      "258",
			DialingCodes: []string{"+689"},
			Name:         "French Polynesia",
		},
		Currencies: []string{"XPF"},
		Languages:  []string{"fra"},
	},
	"PNG": country{
		Country: Country{
			Alpha2:       "PG",
			Alpha3:       "PNG",
			Numeric:      "598",
			DialingCodes: []string{"+675"},
			Name:         "Papua New Guinea",
		},
		Currencies: []string{"PGK"},
		Languages:  []string{"eng"},
	},
	"PHL": country{
		Country: Country{
			Alpha2:       "PH",
			Alpha3:       "PHL",
			Numeric:      "608",
			DialingCodes: []string{"+63"},
			Name:         "Philippines",
		},
		Currencies: []string{"PHP"},
		Languages:  []string{"eng"},
	},
	"PAK": country{
		Country: Country{
			Alpha2:       "PK",
			Alpha3:       "PAK",
			Numeric:      "586",
			DialingCodes: []string{"+92"},
			Name:         "Pakistan",
		},
		Currencies: []string{"PKR"},
		Languages:  []string{"urd", "eng"},
	},
	"POL": country{
		Country: Country{
			Alpha2:       "PL",
			Alpha3:       "POL",
			Numeric:      "616",
			DialingCodes: []string{"+48"},
			Name:         "Poland",
		},
		Currencies: []string{"PLN"},
		Languages:  []string{"pol"},
	},
	"SPM": country{
		Country: Country{
			Alpha2:       "PM",
			Alpha3:       "SPM",
			Numeric:      "666",
			DialingCodes: []string{"+508"},
			Name:         "Saint Pierre And Miquelon",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"eng"},
	},
	"PCN": country{
		Country: Country{
			Alpha2:       "PN",
			Alpha3:       "PCN",
			Numeric:      "612",
			DialingCodes: []string{"+872"},
			Name:         "Pitcairn",
		},
		Currencies: []string{"NZD"},
		Languages:  []string{"eng"},
	},
	"PRI": country{
		Country: Country{
			Alpha2:       "PR",
			Alpha3:       "PRI",
			Numeric:      "630",
			DialingCodes: []string{"+1 787", "+1 939"},
			Name:         "Puerto Rico",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"spa", "eng"},
	},
	"PSE": country{
		Country: Country{
			Alpha2:       "PS",
			Alpha3:       "PSE",
			Numeric:      "275",
			DialingCodes: []string{"+970"},
			Name:         "Palestinian Territory, Occupied",
		},
		Currencies: []string{"JOD", "EGP", "ILS"},
		Languages:  []string{"ara"},
	},
	"PRT": country{
		Country: Country{
			Alpha2:       "PT",
			Alpha3:       "PRT",
			Numeric:      "620",
			DialingCodes: []string{"+351"},
			Name:         "Portugal",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"por"},
	},
	"PLW": country{
		Country: Country{
			Alpha2:       "PW",
			Alpha3:       "PLW",
			Numeric:      "585",
			DialingCodes: []string{"+680"},
			Name:         "Palau",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"PRY": country{
		Country: Country{
			Alpha2:       "PY",
			Alpha3:       "PRY",
			Numeric:      "600",
			DialingCodes: []string{"+595"},
			Name:         "Paraguay",
		},
		Currencies: []string{"PYG"},
		Languages:  []string{"spa"},
	},
	"QAT": country{
		Country: Country{
			Alpha2:       "QA",
			Alpha3:       "QAT",
			Numeric:      "634",
			DialingCodes: []string{"+974"},
			Name:         "Qatar",
		},
		Currencies: []string{"QAR"},
		Languages:  []string{"ara"},
	},
	"REU": country{
		Country: Country{
			Alpha2:       "RE",
			Alpha3:       "REU",
			Numeric:      "638",
			DialingCodes: []string{"+262"},
			Name:         "Reunion",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"ROU": country{
		Country: Country{
			Alpha2:       "RO",
			Alpha3:       "ROU",
			Numeric:      "642",
			DialingCodes: []string{"+40"},
			Name:         "Romania",
		},
		Currencies: []string{"RON"},
		Languages:  []string{"ron"},
	},
	"SRB": country{
		Country: Country{
			Alpha2:       "RS",
			Alpha3:       "SRB",
			Numeric:      "688",
			DialingCodes: []string{"+381"},
			Name:         "Serbia",
		},
		Currencies: []string{"RSD"},
		Languages:  []string{"srp"},
	},
	"RUS": country{
		Country: Country{
			Alpha2:       "RU",
			Alpha3:       "RUS",
			Numeric:      "643",
			DialingCodes: []string{"+7", "+7 3", "+7 4", "+7 8"},
			Name:         "Russian Federation",
		},
		Currencies: []string{"RUB"},
		Languages:  []string{"rus"},
	},
	"RWA": country{
		Country: Country{
			Alpha2:       "RW",
			Alpha3:       "RWA",
			Numeric:      "646",
			DialingCodes: []string{"+250"},
			Name:         "Rwanda",
		},
		Currencies: []string{"RWF"},
		Languages:  []string{"eng", "fra", "kin"},
	},
	"SAU": country{
		Country: Country{
			Alpha2:       "SA",
			Alpha3:       "SAU",
			Numeric:      "682",
			DialingCodes: []string{"+966"},
			Name:         "Saudi Arabia",
		},
		Currencies: []string{"SAR"},
		Languages:  []string{"ara"},
	},
	"SLB": country{
		Country: Country{
			Alpha2:       "SB",
			Alpha3:       "SLB",
			Numeric:      "090",
			DialingCodes: []string{"+677"},
			Name:         "Solomon Islands",
		},
		Currencies: []string{"SBD"},
		Languages:  []string{"eng"},
	},
	"SYC": country{
		Country: Country{
			Alpha2:       "SC",
			Alpha3:       "SYC",
			Numeric:      "690",
			DialingCodes: []string{"+248"},
			Name:         "Seychelles",
		},
		Currencies: []string{"SCR"},
		Languages:  []string{"eng", "fra"},
	},
	"SDN": country{
		Country: Country{
			Alpha2:       "SD",
			Alpha3:       "SDN",
			Numeric:      "729",
			DialingCodes: []string{"+249"},
			Name:         "Sudan",
		},
		Currencies: []string{"SDG"},
		Languages:  []string{"ara", "eng"},
	},
	"SWE": country{
		Country: Country{
			Alpha2:       "SE",
			Alpha3:       "SWE",
			Numeric:      "752",
			DialingCodes: []string{"+46"},
			Name:         "Sweden",
		},
		Currencies: []string{"SEK"},
		Languages:  []string{"swe"},
	},
	"SGP": country{
		Country: Country{
			Alpha2:       "SG",
			Alpha3:       "SGP",
			Numeric:      "702",
			DialingCodes: []string{"+65"},
			Name:         "Singapore",
		},
		Currencies: []string{"SGD"},
		Languages:  []string{"eng", "zho", "msa", "tam"},
	},
	"SHN": country{
		Country: Country{
			Alpha2:       "SH",
			Alpha3:       "SHN",
			Numeric:      "654",
			DialingCodes: []string{"+290"},
			Name:         "Saint Helena, Ascension And Tristan Da Cunha",
		},
		Currencies: []string{"SHP"},
		Languages:  []string{"eng"},
	},
	"SVN": country{
		Country: Country{
			Alpha2:       "SI",
			Alpha3:       "SVN",
			Numeric:      "705",
			DialingCodes: []string{"+386"},
			Name:         "Slovenia",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"slv"},
	},
	"SVK": country{
		Country: Country{
			Alpha2:       "SK",
			Alpha3:       "SVK",
			Numeric:      "703",
			DialingCodes: []string{"+421"},
			Name:         "Slovakia",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"slk"},
	},
	"SLE": country{
		Country: Country{
			Alpha2:       "SL",
			Alpha3:       "SLE",
			Numeric:      "694",
			DialingCodes: []string{"+232"},
			Name:         "Sierra Leone",
		},
		Currencies: []string{"SLL"},
		Languages:  []string{"eng"},
	},
	"SMR": country{
		Country: Country{
			Alpha2:       "SM",
			Alpha3:       "SMR",
			Numeric:      "674",
			DialingCodes: []string{"+378"},
			Name:         "San Marino",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"ita"},
	},
	"SEN": country{
		Country: Country{
			Alpha2:       "SN",
			Alpha3:       "SEN",
			Numeric:      "686",
			DialingCodes: []string{"+221"},
			Name:         "Senegal",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"fra"},
	},
	"SOM": country{
		Country: Country{
			Alpha2:       "SO",
			Alpha3:       "SOM",
			Numeric:      "706",
			DialingCodes: []string{"+252"},
			Name:         "Somalia",
		},
		Currencies: []string{"SOS"},
		Languages:  []string{"som"},
	},
	"SUR": country{
		Country: Country{
			Alpha2:       "SR",
			Alpha3:       "SUR",
			Numeric:      "740",
			DialingCodes: []string{"+597"},
			Name:         "Suriname",
		},
		Currencies: []string{"SRD"},
		Languages:  []string{"nld"},
	},
	"SSD": country{
		Country: Country{
			Alpha2:       "SS",
			Alpha3:       "SSD",
			Numeric:      "728",
			DialingCodes: []string{"+211"},
			Name:         "South Sudan",
		},
		Currencies: []string{"SSP"},
		Languages:  []string{"eng"},
	},
	"STP": country{
		Country: Country{
			Alpha2:       "ST",
			Alpha3:       "STP",
			Numeric:      "678",
			DialingCodes: []string{"+239"},
			Name:         "Sao Tome and Principe",
		},
		Currencies: []string{"STD"},
		Languages:  []string{"por"},
	},
	"SLV": country{
		Country: Country{
			Alpha2:       "SV",
			Alpha3:       "SLV",
			Numeric:      "222",
			DialingCodes: []string{"+503"},
			Name:         "El Salvador",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"spa"},
	},
	"SXM": country{
		Country: Country{
			Alpha2:       "SX",
			Alpha3:       "SXM",
			Numeric:      "534",
			DialingCodes: []string{"+1 721"},
			Name:         "Sint Maarten",
		},
		Currencies: []string{"ANG"},
		Languages:  []string{"nld"},
	},
	"SYR": country{
		Country: Country{
			Alpha2:       "SY",
			Alpha3:       "SYR",
			Numeric:      "760",
			DialingCodes: []string{"+963"},
			Name:         "Syrian Arab Republic",
		},
		Currencies: []string{"SYP"},
		Languages:  []string{"ara"},
	},
	"SWZ": country{
		Country: Country{
			Alpha2:       "SZ",
			Alpha3:       "SWZ",
			Numeric:      "748",
			DialingCodes: []string{"+268"},
			Name:         "Swaziland",
		},
		Currencies: []string{"SZL"},
		Languages:  []string{"eng", "ssw"},
	},
	"TCA": country{
		Country: Country{
			Alpha2:       "TC",
			Alpha3:       "TCA",
			Numeric:      "796",
			DialingCodes: []string{"+1 649"},
			Name:         "Turks And Caicos Islands",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"TCD": country{
		Country: Country{
			Alpha2:       "TD",
			Alpha3:       "TCD",
			Numeric:      "148",
			DialingCodes: []string{"+235"},
			Name:         "Chad",
		},
		Currencies: []string{"XAF"},
		Languages:  []string{"ara", "fra"},
	},
	"ATF": country{
		Country: Country{
			Alpha2:       "TF",
			Alpha3:       "ATF",
			Numeric:      "260",
			DialingCodes: []string{},
			Name:         "French Southern Territories",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"TGO": country{
		Country: Country{
			Alpha2:       "TG",
			Alpha3:       "TGO",
			Numeric:      "768",
			DialingCodes: []string{"+228"},
			Name:         "Togo",
		},
		Currencies: []string{"XOF"},
		Languages:  []string{"fra"},
	},
	"THA": country{
		Country: Country{
			Alpha2:       "TH",
			Alpha3:       "THA",
			Numeric:      "764",
			DialingCodes: []string{"+66"},
			Name:         "Thailand",
		},
		Currencies: []string{"THB"},
		Languages:  []string{"tha"},
	},
	"TJK": country{
		Country: Country{
			Alpha2:       "TJ",
			Alpha3:       "TJK",
			Numeric:      "762",
			DialingCodes: []string{"+992"},
			Name:         "Tajikistan",
		},
		Currencies: []string{"TJS"},
		Languages:  []string{"tgk", "rus"},
	},
	"TKL": country{
		Country: Country{
			Alpha2:       "TK",
			Alpha3:       "TKL",
			Numeric:      "772",
			DialingCodes: []string{"+690"},
			Name:         "Tokelau",
		},
		Currencies: []string{"NZD"},
		Languages:  []string{"eng"},
	},
	"TLS": country{
		Country: Country{
			Alpha2:       "TL",
			Alpha3:       "TLS",
			Numeric:      "626",
			DialingCodes: []string{"+670"},
			Name:         "Timor-Leste, Democratic Republic of",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"por"},
	},
	"TKM": country{
		Country: Country{
			Alpha2:       "TM",
			Alpha3:       "TKM",
			Numeric:      "795",
			DialingCodes: []string{"+993"},
			Name:         "Turkmenistan",
		},
		Currencies: []string{"TMT"},
		Languages:  []string{"tuk", "rus"},
	},
	"TUN": country{
		Country: Country{
			Alpha2:       "TN",
			Alpha3:       "TUN",
			Numeric:      "788",
			DialingCodes: []string{"+216"},
			Name:         "Tunisia",
		},
		Currencies: []string{"TND"},
		Languages:  []string{"ara"},
	},
	"TON": country{
		Country: Country{
			Alpha2:       "TO",
			Alpha3:       "TON",
			Numeric:      "776",
			DialingCodes: []string{"+676"},
			Name:         "Tonga",
		},
		Currencies: []string{"TOP"},
		Languages:  []string{"eng"},
	},
	"TUR": country{
		Country: Country{
			Alpha2:       "TR",
			Alpha3:       "TUR",
			Numeric:      "792",
			DialingCodes: []string{"+90"},
			Name:         "Turkey",
		},
		Currencies: []string{"TRY"},
		Languages:  []string{"tur"},
	},
	"TTO": country{
		Country: Country{
			Alpha2:       "TT",
			Alpha3:       "TTO",
			Numeric:      "780",
			DialingCodes: []string{"+1 868"},
			Name:         "Trinidad And Tobago",
		},
		Currencies: []string{"TTD"},
		Languages:  []string{"eng"},
	},
	"TUV": country{
		Country: Country{
			Alpha2:       "TV",
			Alpha3:       "TUV",
			Numeric:      "798",
			DialingCodes: []string{"+688"},
			Name:         "Tuvalu",
		},
		Currencies: []string{"AUD"},
		Languages:  []string{"eng"},
	},
	"TWN": country{
		Country: Country{
			Alpha2:       "TW",
			Alpha3:       "TWN",
			Numeric:      "158",
			DialingCodes: []string{"+886"},
			Name:         "Taiwan",
		},
		Currencies: []string{"TWD"},
		Languages:  []string{"zho"},
	},
	"TZA": country{
		Country: Country{
			Alpha2:       "TZ",
			Alpha3:       "TZA",
			Numeric:      "834",
			DialingCodes: []string{"+255"},
			Name:         "Tanzania, United Republic Of",
		},
		Currencies: []string{"TZS"},
		Languages:  []string{"swa", "eng"},
	},
	"UKR": country{
		Country: Country{
			Alpha2:       "UA",
			Alpha3:       "UKR",
			Numeric:      "804",
			DialingCodes: []string{"+380"},
			Name:         "Ukraine",
		},
		Currencies: []string{"UAH"},
		Languages:  []string{"ukr", "rus"},
	},
	"UGA": country{
		Country: Country{
			Alpha2:       "UG",
			Alpha3:       "UGA",
			Numeric:      "800",
			DialingCodes: []string{"+256"},
			Name:         "Uganda",
		},
		Currencies: []string{"UGX"},
		Languages:  []string{"eng", "swa"},
	},
	"UMI": country{
		Country: Country{
			Alpha2:       "UM",
			Alpha3:       "UMI",
			Numeric:      "581",
			DialingCodes: []string{"+1"},
			Name:         "United States Minor Outlying Islands",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"USA": country{
		Country: Country{
			Alpha2:       "US",
			Alpha3:       "USA",
			Numeric:      "840",
			DialingCodes: []string{"+1"},
			Name:         "United States",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"URY": country{
		Country: Country{
			Alpha2:       "UY",
			Alpha3:       "URY",
			Numeric:      "858",
			DialingCodes: []string{"+598"},
			Name:         "Uruguay",
		},
		Currencies: []string{"UYU", "UYI"},
		Languages:  []string{"spa"},
	},
	"UZB": country{
		Country: Country{
			Alpha2:       "UZ",
			Alpha3:       "UZB",
			Numeric:      "860",
			DialingCodes: []string{"+998"},
			Name:         "Uzbekistan",
		},
		Currencies: []string{"UZS"},
		Languages:  []string{"uzb", "rus"},
	},
	"VAT": country{
		Country: Country{
			Alpha2:       "VA",
			Alpha3:       "VAT",
			Numeric:      "336",
			DialingCodes: []string{"+379", "+39"},
			Name:         "Vatican City State",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"ita"},
	},
	"VCT": country{
		Country: Country{
			Alpha2:       "VC",
			Alpha3:       "VCT",
			Numeric:      "670",
			DialingCodes: []string{"+1 784"},
			Name:         "Saint Vincent And The Grenadines",
		},
		Currencies: []string{"XCD"},
		Languages:  []string{"eng"},
	},
	"VEN": country{
		Country: Country{
			Alpha2:       "VE",
			Alpha3:       "VEN",
			Numeric:      "862",
			DialingCodes: []string{"+58"},
			Name:         "Venezuela, Bolivarian Republic Of",
		},
		Currencies: []string{"VEF"},
		Languages:  []string{"spa"},
	},
	"VGB": country{
		Country: Country{
			Alpha2:       "VG",
			Alpha3:       "VGB",
			Numeric:      "092",
			DialingCodes: []string{"+1 284"},
			Name:         "Virgin Islands (British)",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"VIR": country{
		Country: Country{
			Alpha2:       "VI",
			Alpha3:       "VIR",
			Numeric:      "850",
			DialingCodes: []string{"+1 340"},
			Name:         "Virgin Islands (US)",
		},
		Currencies: []string{"USD"},
		Languages:  []string{"eng"},
	},
	"VNM": country{
		Country: Country{
			Alpha2:       "VN",
			Alpha3:       "VNM",
			Numeric:      "704",
			DialingCodes: []string{"+84"},
			Name:         "Viet Nam",
		},
		Currencies: []string{"VND"},
		Languages:  []string{"vie"},
	},
	"VUT": country{
		Country: Country{
			Alpha2:       "VU",
			Alpha3:       "VUT",
			Numeric:      "548",
			DialingCodes: []string{"+678"},
			Name:         "Vanuatu",
		},
		Currencies: []string{"VUV"},
		Languages:  []string{"bis", "eng", "fra"},
	},
	"WLF": country{
		Country: Country{
			Alpha2:       "WF",
			Alpha3:       "WLF",
			Numeric:      "876",
			DialingCodes: []string{"+681"},
			Name:         "Wallis And Futuna",
		},
		Currencies: []string{"XPF"},
		Languages:  []string{"fra"},
	},
	"WSM": country{
		Country: Country{
			Alpha2:       "WS",
			Alpha3:       "WSM",
			Numeric:      "882",
			DialingCodes: []string{"+685"},
			Name:         "Samoa",
		},
		Currencies: []string{"WST"},
		Languages:  []string{"eng", "smo"},
	},
	"YEM": country{
		Country: Country{
			Alpha2:       "YE",
			Alpha3:       "YEM",
			Numeric:      "887",
			DialingCodes: []string{"+967"},
			Name:         "Yemen",
		},
		Currencies: []string{"YER"},
		Languages:  []string{"ara"},
	},
	"MYT": country{
		Country: Country{
			Alpha2:       "YT",
			Alpha3:       "MYT",
			Numeric:      "175",
			DialingCodes: []string{"+262"},
			Name:         "Mayotte",
		},
		Currencies: []string{"EUR"},
		Languages:  []string{"fra"},
	},
	"ZAF": country{
		Country: Country{
			Alpha2:       "ZA",
			Alpha3:       "ZAF",
			Numeric:      "710",
			DialingCodes: []string{"+27"},
			Name:         "South Africa",
		},
		Currencies: []string{"ZAR"},
		Languages:  []string{"afr", "eng", "nbl", "som", "tso", "ven", "xho", "zul"},
	},
	"ZMB": country{
		Country: Country{
			Alpha2:       "ZM",
			Alpha3:       "ZMB",
			Numeric:      "894",
			DialingCodes: []string{"+260"},
			Name:         "Zambia",
		},
		Currencies: []string{"ZMW"},
		Languages:  []string{"eng"},
	},
	"ZWE": country{
		Country: Country{
			Alpha2:       "ZW",
			Alpha3:       "ZWE",
			Numeric:      "716",
			DialingCodes: []string{"+263"},
			Name:         "Zimbabwe",
		},
		Currencies: []string{"USD", "ZAR", "BWP", "GBP", "EUR"},
		Languages:  []string{"eng", "sna", "nde"},
	},
}
